apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdiviz-valuematch
  labels:
    app: bdiviz-valuematch
spec:
  # Run two copies of the Pod
  replicas: 1
  # Perform rolling updates, starting containers before stopping the old ones
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      # This is how the Deployment recognizes its Pods, has to match the labels
      # of the Pod template
      app: bdiviz-valuematch
  template:
    metadata:
      labels:
        app: bdiviz-valuematch
    spec:
      containers:
        # Here's our Flask container
        - name: bdiviz-app-valuematch
          # Put your own image here
          image: edenwu/bdi-viz-react:amd64-valuemapping
          imagePullPolicy: "Always"
          ports:
            # This is the port we'll expose to the internet eventually
            - name: web
              containerPort: 3000
          resources:
            requests:
              cpu: "4000m"
              memory: "20Gi"
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bdiviz-env-var
                  key: openai_api_key
            - name: LANGCHAIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bdiviz-env-var
                  key: langchain_api_key
            - name: PORTKEY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bdiviz-env-var
                  key: portkey_api_key
            - name: PROVIDER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bdiviz-env-var
                  key: provider_api_key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdiviz-valuematch-backup-a
  labels:
    app: bdiviz-valuematch-backup-a
spec:
  # Run two copies of the Pod
  replicas: 1
  # Perform rolling updates, starting containers before stopping the old ones
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      # This is how the Deployment recognizes its Pods, has to match the labels
      # of the Pod template
      app: bdiviz-valuematch-backup-a
  template:
    metadata:
      labels:
        app: bdiviz-valuematch-backup-a
    spec:
      containers:
        # Here's our Flask container
        - name: bdiviz-app-valuematch-backup-a
          # Put your own image here
          image: edenwu/bdi-viz-react:amd64-valuemapping
          imagePullPolicy: "Always"
          ports:
            # This is the port we'll expose to the internet eventually
            - name: web
              containerPort: 3000
          resources:
            requests:
              cpu: "4000m"
              memory: "20Gi"
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bdiviz-env-var
                  key: openai_api_key
            - name: LANGCHAIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bdiviz-env-var
                  key: langchain_api_key
            - name: PORTKEY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bdiviz-env-var
                  key: portkey_api_key
            - name: PROVIDER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bdiviz-env-var
                  key: provider_api_key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdiviz-valuematch-backup-b
  labels:
    app: bdiviz-valuematch-backup-b
spec:
  # Run two copies of the Pod
  replicas: 1
  # Perform rolling updates, starting containers before stopping the old ones
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      # This is how the Deployment recognizes its Pods, has to match the labels
      # of the Pod template
      app: bdiviz-valuematch-backup-b
  template:
    metadata:
      labels:
        app: bdiviz-valuematch-backup-b
    spec:
      containers:
        # Here's our Flask container
        - name: bdiviz-app-valuematch-backup-b
          # Put your own image here
          image: edenwu/bdi-viz-react:amd64-valuemapping
          imagePullPolicy: "Always"
          ports:
            # This is the port we'll expose to the internet eventually
            - name: web
              containerPort: 3000
          resources:
            requests:
              cpu: "4000m"
              memory: "20Gi"
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bdiviz-env-var
                  key: openai_api_key
            - name: LANGCHAIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bdiviz-env-var
                  key: langchain_api_key
            - name: PORTKEY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bdiviz-env-var
                  key: portkey_api_key
            - name: PROVIDER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bdiviz-env-var
                  key: provider_api_key